<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-P1434LQ" failures="0" tests="8" name="TestCases.LoginTest" time="71.927" errors="1" timestamp="2024-07-28T05:45:25 GMT-11:00" skipped="0">
  <testcase classname="TestCases.LoginTest" name="TC03_LoginSuccessTest" time="6.886"/>
  <system-out/>
  <testcase classname="TestCases.LoginTest" name="TC04_LoginSuccessTest" time="10.774"/>
  <system-out/>
  <testcase classname="TestCases.LoginTest" name="TC01_LoginFailureTest" time="7.228">
    <error message="expected:&lt;The email or password you have entered is invalid&gt; but was:&lt;Please enter a valid email address&gt;" type="junit.framework.ComparisonFailure">
      <![CDATA[junit.framework.ComparisonFailure: expected:<The email or password you have entered is invalid> but was:<Please enter a valid email address>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at Pages.LoginPage.ValidateErrorMsg(LoginPage.java:46)
at TestCases.LoginTest.TC01_LoginFailureTest(LoginTest.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- TC01_LoginFailureTest -->
  <system-out/>
  <testcase classname="TestCases.LoginTest" name="TC04_LoginSuccessTest" time="10.230"/>
  <system-out/>
  <testcase classname="TestCases.LoginTest" name="TC04_LoginSuccessTest" time="9.994"/>
  <system-out/>
  <testcase classname="TestCases.LoginTest" name="TC04_LoginSuccessTest" time="9.511"/>
  <system-out/>
  <testcase classname="TestCases.LoginTest" name="TC02_LoginSuccessTest" time="6.760"/>
  <system-out/>
  <testcase classname="TestCases.LoginTest" name="TC04_LoginSuccessTest" time="10.544"/>
  <system-out/>
</testsuite> <!-- TestCases.LoginTest -->
